name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP package
        run: zip -r hackernews-dark-theme.zip . -x "*.git*"

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: hackernews-dark-theme
          path: hackernews-dark-theme.zip

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: hackernews-dark-theme.zip
          name: Latest Build
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}